export {
  StarfieldBackground,
  getStarfieldBackgroundGeometry,
  getStarfieldBackgroundMotionConfig,
  starfieldBackgroundClassNames,
  starfieldBackgroundContentClassNames,
  starfieldBackgroundLayerClassNames,
  type StarfieldBackgroundClassNamesOptions,
  type StarfieldBackgroundContentClassNamesOptions,
  type StarfieldBackgroundDensity,
  type StarfieldBackgroundIntensity,
  type StarfieldBackgroundLayer,
  type StarfieldBackgroundLayerClassNamesOptions,
  type StarfieldBackgroundMotionConfig,
  type StarfieldBackgroundProps,
  type StarfieldBackgroundSpeed,
  type StarfieldBackgroundStar,
  type StarfieldBackgroundTone,
  type StarfieldBackgroundTwinkle,
} from "./starfield-background";
