export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  dialogClassNames,
  dialogContentClassNames,
  dialogDescriptionClassNames,
  dialogFooterClassNames,
  dialogHeaderClassNames,
  dialogOverlayClassNames,
  dialogTitleClassNames,
  dialogTriggerClassNames,
  type DialogCloseProps,
  type DialogContentProps,
  type DialogDescriptionProps,
  type DialogFooterProps,
  type DialogHeaderProps,
  type DialogProps,
  type DialogScrollBehavior,
  type DialogSize,
  type DialogTitleProps,
  type DialogTriggerProps,
} from "./dialog";
