export {
  HeroTextAnimation,
  HeroTextAnimationProvider,
  heroTextAnimationClassNames,
  heroTextAnimationMotionTokens,
  splitHeroText,
  type HeroTextAnimationElement,
  type HeroTextAnimationKind,
  type HeroTextAnimationProps,
  type HeroTextAnimationProviderProps,
  type HeroTextAnimationProviderReducedMotion,
  type HeroTextAnimationReducedMotionStrategy,
  type HeroTextAnimationSegment,
  type HeroTextAnimationSplitBy,
  type HeroTextAnimationSvgPath,
  type HeroTextAnimationTrigger,
} from "./hero-text-animation";
