export {
  AuroraBackground,
  auroraBackgroundClassNames,
  auroraBackgroundContentClassNames,
  auroraBackgroundHueShifts,
  auroraBackgroundLayerClassNames,
  getAuroraBackgroundGeometry,
  getAuroraBackgroundMotionConfig,
  type AuroraBackgroundClassNamesOptions,
  type AuroraBackgroundContentClassNamesOptions,
  type AuroraBackgroundDensity,
  type AuroraBackgroundIntensity,
  type AuroraBackgroundLayerClassNamesOptions,
  type AuroraBackgroundMotionConfig,
  type AuroraBackgroundProps,
  type AuroraBackgroundRibbon,
  type AuroraBackgroundSpeed,
  type AuroraBackgroundTone,
} from "./aurora-background";
